### ISSUE TITLE
`error: implicit declaration of function ‘aws_event_loop_schedule_task_now_serialized’; did you mean ‘aws_channel_schedule_task_now_serialized’`

### ISSUE THREAD

**Issue by giordano** [awslabs/aws-c-event-stream#134]
### Describe the bug

Compiling v0.5.7 of this package with gcc 14 fails with
```
[23:25:36] /opt/bin/riscv64-linux-gnu-libgfortran5-cxx11/riscv64-linux-gnu-gcc --sysroot=/opt/riscv64-linux-gnu/riscv64-linux-gnu/sys-root/ -DAWS_CAL_USE_IMPORT_EXPORT -DAWS_CHECKSUMS_USE_IMPORT_EXPORT -DAWS_COMMON_USE_IMPORT_EXPORT -DAWS_ENABLE_EPOLL -DAWS_EVENT_STREAM_EXPORTS -DAWS_EVENT_STREAM_USE_IMPORT_EXPORT -DAWS_IO_USE_IMPORT_EXPORT -DHAVE_SYSCONF -DINTEL_NO_ITTNOTIFY_API -Daws_c_event_stream_EXPORTS -I/workspace/srcdir/aws-c-event-stream/include -O3 -DNDEBUG -fPIC -fvisibility=hidden -Wall -Wstrict-prototypes -Wextra -pedantic -Wno-long-long -fPIC -std=gnu99 -MD -MT CMakeFiles/aws-c-event-stream.dir/source/event_stream_rpc_client.c.o -MF CMakeFiles/aws-c-event-stream.dir/source/event_stream_rpc_client.c.o.d -o CMakeFiles/aws-c-event-stream.dir/source/event_stream_rpc_client.c.o -c /workspace/srcdir/aws-c-event-stream/source/event_stream_rpc_client.c
[23:25:37] /workspace/srcdir/aws-c-event-stream/source/event_stream_rpc_client.c: In function ‘s_send_protocol_message’:
[23:25:37] /workspace/srcdir/aws-c-event-stream/source/event_stream_rpc_client.c:890:5: error: implicit declaration of function ‘aws_event_loop_schedule_task_now_serialized’; did you mean ‘aws_channel_schedule_task_now_serialized’? [-Wimplicit-function-declaration]
[23:25:37]   890 |     aws_event_loop_schedule_task_now_serialized(connection->event_loop, &task->base);
[23:25:37]       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[23:25:37]       |     aws_channel_schedule_task_now_serialized
```

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Expected Behavior

Compilation is successful.

### Current Behavior

Compilation fails due to implicit reference to function.

### Reproduction Steps

```
cmake -DBUILD_TESTING=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON
cmake --build . --target install
```

### Additional Information/Context

Broken by #133.

### aws-c-event-stream version used

v0.5.7

### Compiler and version used

GCC 14

### Operating System and version

Not relevant
